version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13
    commands:
      - python -m venv src/.venv
      - . src/.venv/bin/activate
      - pip install --upgrade pip
      - pip install -r src/requirements.txt
  build:
    commands:
      - python src/run.py lint
      - python src/run.py test
