version: 0.2

env:
  variables:
    APP_NAME: "python-sample-app"

phases:
  install:
    commands:
      # Start the Docker daemon
      - echo "Starting Docker daemon..."
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      # Wait for the Docker daemon to be fully ready
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - echo "Checking AWS CLI version..."
      - aws --version
      # Manually install AWS CLI v2 (optional if your image already has it)
      - echo "Checking AWS CLI version..."
      - aws --version

  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | \
        docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - docker build -t $APP_NAME .
      - docker tag $APP_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APP_NAME:latest
      - docker tag $APP_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APP_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION

  post_build:
    commands:
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APP_NAME:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$APP_NAME:$CODEBUILD_RESOLVED_SOURCE_VERSION
