name: workflow-for-Python-app
on:
   push:
      branches:
        - main
   workflow_dispatch:
jobs:
   job1-testing:
     runs-on: ubuntu-latest
     steps:
       - name: checkout the code
         uses: actions/checkout@v5
       - name: setup the Python environment
         uses: actions/setup-python@v6
         with:
           python-version: '3.13'
       - name: Cache Python dependencies
         id: cache-deps
         uses: actions/cache@v4
         with:
          path: |
            ~/.cache/pip
            .venv
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-python-

       - name: Install dependencies
         if: steps.cache-deps.outputs.cache-hit != 'true'
         run:  |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
         working-directory: ./src
       - name: Linting...
         run: python run.py lint
         working-directory: ./src
       - name: Run the tests
         run:  .venv/bin/python -m pytest -v
         working-directory: ./src

   

       
   